const gridImagesA = [
  {
    id: 1,
    path: "/yorunoume.png",
    name: "夜の梅",
    nameen: "illust-ukiyoe",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
    bgc: "",
    cover: true,
  },
  {
    id: 2,
    path: "/gridImage_02.png",
    name: "ミチオシエ",
    nameen: "list",
    tool: "affinity designer",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
    bgc: "#6e0b0b",
    cover: true,
  },
  {
    id: 3,
    path: "/gridImage_03.png",
    name: "アマゾネス",
    nameen: "illust-tsuboe",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
    bgc: "",
    cover: true,
  },
  {
    id: 4,
    path: "/gridImage_04.png",
    name: "雲龍",
    nameen: "magazine",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
    bgc: "#4f2750",
    cover: true,
  },
  {
    id: 5,
    path: "/gridImage_05.png",
    name: "扇子を持つ女",
    nameen: "illust-umi",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
    bgc: "#9b1dab",
    cover: true,
  },
  {
    id: 6,
    path: "/gridImage_06.png",
    name: "春の嵐",
    nameen: "illust-flog",
    icon: [],
    bgc: "",
    cover: false,
  },
  {
    id: 7,
    path: "/gridImage_07.png",
    name: "船出",
    nameen: "illust-sea",
    icon: [],
    bgc: "",
    cover: false,
  },
  {
    id: 8,
    path: "/gridImage_08.png",
    name: "ともしび",
    nameen: "illust-grasshopper",
    icon: [],
    bgc: "",
    cover: false,
  },
  {
    id: 9,
    path: "/gridImage_09.png",
    name: "休息",
    nameen: "illust-seagull",
    icon: [],
    bgc: "",
    cover: false,
  },
  {
    id: 10,
    path: "/gridImage_10.png",
    name: "三日月夜",
    nameen: "illust-penguin",
    icon: [],
    bgc: "",
    cover: false,
  },
  {
    id: 11,
    path: "/kisyu_black.png",
    name: "騎手（黒絵）",
    nameen: "illust-kishu",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
    bgc: "",
    cover: true,
  },
  {
    id: 12,
    path: "/war_red.png",
    name: "ペルシャ戦争",
    nameen: "list",
    tool: "affinity designer",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
    bgc: "#6e0b0b",
    cover: true,
  },
  {
    id: 13,
    path: "/touhukozouA.png",
    name: "豆腐小僧",
    nameen: "illust-tsuboe",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
    bgc: "grey",
    cover: true,
  },
  {
    id: 14,
    path: "/utamaro_01.png",
    name: "雲龍",
    nameen: "magazine",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
    bgc: "#4f2750",
    cover: true,
  },
  {
    id: 15,
    path: "/kamikiri.png",
    name: "扇子を持つ女",
    nameen: "illust-umi",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
    bgc: "#9b1dab",
    cover: false,
  },
  {
    id: 16,
    path: "/kabukiyakusha_01.png",
    name: "春の嵐",
    nameen: "illust-flog",
    icon: [],
    bgc: "",
    cover: false,
  },
  {
    id: 17,
    path: "/kabukiyakusha_02.png",
    name: "船出",
    nameen: "illust-sea",
    icon: [],
    bgc: "",
    cover: false,
  },
  {
    id: 18,
    path: "/touhukozouA.png",
    name: "ともしび",
    nameen: "illust-grasshopper",
    icon: [],
    bgc: "",
    cover: false,
  },
  {
    id: 19,
    path: "/toufukozouB.png",
    name: "休息",
    nameen: "illust-seagull",
    icon: [],
    bgc: "",
    cover: false,
  },
  {
    id: 20,
    path: "/hitotsumekozou.png",
    name: "三日月夜",
    nameen: "illust-penguin",
    icon: [],
    bgc: "",
    cover: false,
  },
];
export { gridImagesA };
