const gridImagesA = [
  {
    id: 1,
    path: "/gridImage_01.png",
    name: "夜の梅",
    nameen: "illust-ukiyoe",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
  },
  {
    id: 2,
    path: "/gridImage_02.png",
    name: "ミチオシエ",
    nameen: "list",
    tool: "affinity designer",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
  },
  {
    id: 3,
    path: "/gridImage_03.png",
    name: "アマゾネス",
    nameen: "illust-tsuboe",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
  },
  {
    id: 4,
    path: "/gridImage_04.png",
    name: "雲龍",
    nameen: "magazine",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
  },
  {
    id: 5,
    path: "/gridImage_05.png",
    name: "扇子を持つ女",
    nameen: "illust-umi",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
  },
  {
    id: 6,
    path: "/gridImage_06.png",
    name: "蛙",
    nameen: "illust-flog",
    icon: [],
  },
  {
    id: 7,
    path: "/gridImage_07.png",
    name: "海",
    nameen: "illust-sea",
    icon: [],
  },
  {
    id: 8,
    path: "/gridImage_08.png",
    name: "バッタ",
    nameen: "illust-grasshopper",
    icon: [],
  },
  {
    id: 9,
    path: "/gridImage_09.png",
    name: "カモメ",
    nameen: "illust-seagull",
    icon: [],
  },
  {
    id: 10,
    path: "/gridImage_10.png",
    name: "ペンギン",
    nameen: "illust-penguin",
    icon: [],
  },
];
export { gridImagesA };
