const gridImagesA = [
  {
    id: 1,
    path: "/gridImage_01.png",
    name: "夜の梅",
    nameen: "illust-ukiyoe",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
    bgc: "",
  },
  {
    id: 2,
    path: "/gridImage_02.png",
    name: "ミチオシエ",
    nameen: "list",
    tool: "affinity designer",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
    bgc: "#6e0b0b",
  },
  {
    id: 3,
    path: "/gridImage_03.png",
    name: "アマゾネス",
    nameen: "illust-tsuboe",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
    bgc: "",
  },
  {
    id: 4,
    path: "/gridImage_04.png",
    name: "雲龍",
    nameen: "magazine",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
    bgc: "#4f2750",
  },
  {
    id: 5,
    path: "/gridImage_05.png",
    name: "扇子を持つ女",
    nameen: "illust-umi",
    icon: [{ src: "/affinity_designer_icon.png", name: "affinity-designer" }],
    bgc: "#9b1dab",
  },
  {
    id: 6,
    path: "/gridImage_06.png",
    name: "春の嵐",
    nameen: "illust-flog",
    icon: [],
    bgc: "",
  },
  {
    id: 7,
    path: "/gridImage_07.png",
    name: "船出",
    nameen: "illust-sea",
    icon: [],
    bgc: "",
  },
  {
    id: 8,
    path: "/gridImage_08.png",
    name: "ともしび",
    nameen: "illust-grasshopper",
    icon: [],
    bgc: "",
  },
  {
    id: 9,
    path: "/gridImage_09.png",
    name: "休息",
    nameen: "illust-seagull",
    icon: [],
    bgc: "",
  },
  {
    id: 10,
    path: "/gridImage_10.png",
    name: "月の夜",
    nameen: "illust-penguin",
    icon: [],
    bgc: "",
  },
];
export { gridImagesA };
